import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../css/style.css', import.meta.url), 'utf8');
const app = readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
const checklistUi = readFileSync(new URL('../js/checklist-ui.js', import.meta.url), 'utf8');

assert.match(html, /data-view="OPERATIONS">교육운영/);
assert.match(html, /<button id="home-button"[^>]*class="settings-button nav-button home-button"[^>]*aria-label="홈"[^>]*title="홈"[^>]*>[\s\S]*?<svg[^>]*viewBox="0 0 24 24"[\s\S]*?<\/svg>[\s\S]*?<\/button>\s*<button[^>]*data-view="OPERATIONS">교육운영<\/button>/);
const homeButtonMarkup = html.match(/<button id="home-button"[\s\S]*?<\/button>/)?.[0] ?? '';
assert.doesNotMatch(homeButtonMarkup, /data-view=/);
assert.match(html, /<title>수습기자 기본교육 운영<\/title>/);
assert.doesNotMatch(html, /수습기자 기본교육 운영 미니리더/);
assert.match(html, /data-checklist-summary="current"/);
assert.match(html, /data-checklist-summary="percent"/);
assert.match(html, /checklist-kpi-card/);
assert.match(html, /checklist-kpi-label">진행중/);
assert.match(html, /id="settings-button"[^>]*>교육일정/);
assert.match(html, /data-view="BUDGET">예산·정산/);
assert.match(html, /id="management-menu-button"[^>]*>더보기/);
assert.match(html, /id="task-admin-button"[^>]*>업무기준 관리/);
assert.match(html, /id="handover-button"[^>]*data-view="HANDOVER"/);
assert.match(html, /id="gap-analysis-button"[^>]*data-view="GAP"/);
assert.match(html, /id="operations-view"/);
assert.doesNotMatch(html, /<h2 id="checklist-title">교육운영<\/h2>/);
assert.match(html, /class="checklist-current-label"/);
assert.match(html, /class="checklist-meta-line"/);
assert.match(styles, /@media \(min-width:1366px\)/);
assert.match(styles, /grid-template-columns:repeat\(6, minmax\(0, 1fr\)\)/);
assert.match(styles, /height:112px; min-height:112px/);
assert.match(styles, /font-family:'Pretendard','SUIT',system-ui/);
assert.match(styles, /font-size:36px !important/);
assert.match(styles, /checklist-kpi-current > strong \{ color:#fff !important/);
assert.match(styles, /checklist-summary-caption \{ overflow:hidden/);
assert.match(html, /id="task-admin-view"/);
assert.doesNotMatch(html, /id="checklist-button"/);
assert.doesNotMatch(html, /id="dashboard-button"/);
assert.match(app, /function showView\(viewName\)/);
assert.match(app, /querySelector\('#home-button'\)\?\.addEventListener\('click', \(\) => \{\s*showView\('OPERATIONS'\);/);
assert.match(styles, /\.home-button \{ width:42px; height:42px; min-height:42px; padding:0; display:inline-flex; align-items:center; justify-content:center; \}/);
assert.match(styles, /\.home-button svg \{ width:19px; height:19px; \}/);
assert.match(styles, /\.nav-button:focus-visible, \.home-button:focus-visible/);
assert.match(checklistUi, /class="checklist-list"/);
assert.match(checklistUi, /checklist-section-block/);
assert.match(checklistUi, /data-checklist-action="toggle-details"/);
assert.match(app, /function renderChecklistSteps/);
assert.match(app, /checklist-step-current/);
assert.match(app, /data-checklist-section-select/);
assert.match(app, /function renderChecklistPrioritySummary/);
assert.match(checklistUi, /다음 구간 미리보기/);

console.log('ux-navigation.test.js passed');
